name: "🐛 SDK Bug Report"
description: "Submit a bug report to help us improve"
title: "🐛 SDK Bug Report: "
labels: [bug]
body:
  - type: dropdown
    id: components
    attributes:
      label: "Which component are you facing issues with?"
      options:
        - Godot SDK Generator
        - GDScript SDK Generator
        - Generated Godot Client SDK
        - Generated GDScript Server SDK
        - Documentation
        - Examples
        - Other
    validations:
      required: true
  - type: input
    id: godot-version
    attributes:
      label: "🎮 Godot Version"
      placeholder: "4.4.1, 4.5.beta, 4.6.dev..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "When I ..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected behavior"
      description: "What did you think would happen?"
      placeholder: "It should ..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "👎 Actual Behavior"
      description: "What did actually happen? Add screenshots, if applicable."
      placeholder: "It actually ..."
  - type: dropdown
    id: operating-system
    attributes:
      label: "💻 Operating system"
      description: "What OS is your server / device running on?"
      options:
        - Linux
        - MacOS
        - Windows
        - Something else
    validations:
      required: true
  - type: textarea
    id: platform
    validations:
      required: false
    attributes:
      label: "🎯 Target Platform"
      description: "Where are you running the generated SDK?"
      placeholder: "Windows, Linux, Android, Web, Dedicated Server..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar bug?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true